'use client';

import { useEffect, useState } from 'react';
import { Save, UserPlus } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { AppSettings, Discount, FeatureFlags, Product, Profile, Role, Station } from '@/lib/types';
import { money } from '@/lib/format';

const stations: [Station, string][] = [['waffle','Waffle'],['chole','Chole Kulche'],['pav','Pav Bataka']];
const roles: Role[] = ['admin','manager','cashier','kitchen','treasurer'];
const featureLabels: Record<keyof FeatureFlags, string> = { cashier:'Cashier', kitchen:'Kitchen', dashboard:'Dashboard', orders:'Order Management', menuManagement:'Menu Management', discounts:'Discounts', staffManagement:'Staff Management', reports:'Reports', printing:'Receipt Printing', customDiscount:'Custom Discounts', cashChange:'Cash / Change', upiPayment:'UPI Payments', posPayment:'POS / Card Payments' };

type UserRow = Profile;

export default function Admin({ settings, profile, onSettingsChange }: { settings: AppSettings; profile: Profile; onSettingsChange: (s: AppSettings) => void }) {
  const [tab, setTab] = useState<'menu'|'discounts'|'staff'|'settings'>('menu');
  const [products, setProducts] = useState<Product[]>([]);
  const [discounts, setDiscounts] = useState<Discount[]>([]);
  const [users, setUsers] = useState<UserRow[]>([]);
  const [form, setForm] = useState({ name:'', price:'', station:'waffle' as Station, category:'' });
  const [df, setDf] = useState({ name:'', type:'percent' as 'percent'|'fixed', value:'10', min:'0', max:'' });
  const [userForm, setUserForm] = useState({ name:'', email:'', password:'', role:'cashier' as Role });
  const [localSettings, setLocalSettings] = useState(settings);
  const [msg, setMsg] = useState('');

  const canStaff = profile.role === 'admin';
  useEffect(() => { setLocalSettings(settings); }, [settings]);
  useEffect(() => { loadProducts(); loadDiscounts(); if (canStaff) loadUsers(); }, [canStaff]);
  async function loadProducts() { const { data } = await supabase.from('products').select('*').order('station').order('sort_order').order('created_at'); setProducts((data ?? []) as Product[]); }
  async function loadDiscounts() { const { data } = await supabase.from('discounts').select('*').order('created_at'); setDiscounts((data ?? []) as Discount[]); }
  async function loadUsers() { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; const r = await fetch('/api/admin/users', { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await r.json(); setUsers(body.users ?? []); }
  async function addProduct() { if (!form.name || !form.price) return; const { error } = await supabase.from('products').insert({ name:form.name.trim(), price:Number(form.price), station:form.station, category:form.category.trim() || null, sort_order:products.filter(p => p.station===form.station).length+1 }); setMsg(error?.message ?? 'Product added'); if (!error) { setForm({ name:'', price:'', station:form.station, category:'' }); loadProducts(); } }
  async function toggleProduct(p: Product) { await supabase.from('products').update({ active:!p.active }).eq('id',p.id); loadProducts(); }
  async function addDiscount() { if (!df.name || !df.value) return; const payload = { name:df.name.trim(), type:df.type, value:Number(df.value), min_order_amount:Number(df.min)||0, max_discount_amount:df.max ? Number(df.max) : null, active:true }; const { error } = await supabase.from('discounts').insert(payload); setMsg(error?.message ?? 'Discount added'); if (!error) { setDf({ name:'', type:'percent', value:'10', min:'0', max:'' }); loadDiscounts(); } }
  async function toggleDiscount(d: Discount) { await supabase.from('discounts').update({ active:!d.active }).eq('id',d.id); loadDiscounts(); }
  async function createUser() { if (!userForm.name || !userForm.email || userForm.password.length<6) return; const { data: { session } } = await supabase.auth.getSession(); if (!session) return; const r = await fetch('/api/admin/users', { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${session.access_token}`}, body:JSON.stringify({ display_name:userForm.name, email:userForm.email, password:userForm.password, role:userForm.role }) }); const body=await r.json(); setMsg(body.error ?? 'User created'); if (r.ok) { setUserForm({ name:'', email:'', password:'', role:'cashier' }); loadUsers(); } }
  async function updateUser(u: UserRow, patch: Record<string, unknown>) { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({id:u.id,...patch})}); const body=await r.json(); if (!r.ok) setMsg(body.error ?? 'Could not update user'); else loadUsers(); }
  async function saveSettings() { const payload={...localSettings,features:{...localSettings.features}}; const { error }=await supabase.from('app_settings').update(payload).eq('id',1); setMsg(error?.message ?? 'Settings saved'); if (!error) onSettingsChange(payload); }
  function featureToggle(key: keyof FeatureFlags) { setLocalSettings(s => ({...s, features:{...s.features,[key]:!s.features[key]}})); }

  const tabs = (['menu','discounts','staff','settings'] as const).filter(t => t==='menu' ? settings.features.menuManagement : t==='discounts' ? settings.features.discounts : t==='staff' ? settings.features.staffManagement && canStaff : canStaff);
  return <main className="container"><div className="rolebar"><div><span>Management</span><p className="hint">Menu, offers, staff access and event controls.</p></div></div><div className="tabs innerTabs">{tabs.map(t=><button key={t} className={'tab '+(tab===t?'active':'')} onClick={()=>setTab(t as any)}>{t==='menu'?'Menu':t==='staff'?'Staff & Roles':t==='discounts'?'Discounts':'Settings'}</button>)}</div>
    {tab==='menu' && <><section className="card"><h2>Add Product</h2><div className="formgrid wide"><input placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Price ₹" inputMode="numeric" value={form.price} onChange={e=>setForm({...form,price:e.target.value.replace(/\D/g,'')})}/><select value={form.station} onChange={e=>setForm({...form,station:e.target.value as Station})}>{stations.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select><input placeholder="Category (optional)" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><button className="primary" onClick={addProduct}>ADD</button></div></section><section className="card sectionSpace"><div className="sectionHead"><h2>Products</h2><button className="secondary" onClick={loadProducts}>Refresh</button></div>{products.map(p=><div className="adminline" key={p.id}><div><b>{p.name}</b><small>{p.station} • {p.category ?? 'Uncategorised'} • {money(p.price,settings.currency_symbol)}</small></div><button className={p.active?'secondary':'primary'} onClick={()=>toggleProduct(p)}>{p.active?'ACTIVE':'INACTIVE'}</button></div>)}</section></>}
    {tab==='discounts' && <><section className="card"><h2>Add Discount</h2><div className="formgrid wide"><input placeholder="Offer name" value={df.name} onChange={e=>setDf({...df,name:e.target.value})}/><select value={df.type} onChange={e=>setDf({...df,type:e.target.value as any})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select><input placeholder={df.type==='percent'?'Value %':'Amount ₹'} inputMode="numeric" value={df.value} onChange={e=>setDf({...df,value:e.target.value.replace(/\D/g,'')})}/><input placeholder="Minimum order ₹" inputMode="numeric" value={df.min} onChange={e=>setDf({...df,min:e.target.value.replace(/\D/g,'')})}/><input placeholder="Max discount ₹ (optional)" inputMode="numeric" value={df.max} onChange={e=>setDf({...df,max:e.target.value.replace(/\D/g,'')})}/><button className="primary" onClick={addDiscount}>ADD</button></div></section><section className="card sectionSpace"><h2>Discounts</h2>{discounts.map(d=><div className="adminline" key={d.id}><div><b>{d.name}</b><small>{d.type==='percent'?`${d.value}%`:money(d.value,settings.currency_symbol)} • min {money(d.min_order_amount,settings.currency_symbol)}{d.max_discount_amount?` • cap ${money(d.max_discount_amount,settings.currency_symbol)}`:''}</small></div><button className={d.active?'secondary':'primary'} onClick={()=>toggleDiscount(d)}>{d.active?'ACTIVE':'INACTIVE'}</button></div>)}</section></>}
    {tab==='staff' && canStaff && <><section className="card"><h2>Add Staff User</h2><p className="hint">Creates a Supabase Auth login and assigns the selected RBAC role.</p><div className="formgrid wide"><input placeholder="Display name" value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/><input type="email" placeholder="Email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/><input type="password" placeholder="Initial password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/><select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value as Role})}>{roles.map(r=><option key={r} value={r}>{r.toUpperCase()}</option>)}</select><button className="primary" onClick={createUser}><UserPlus size={17}/> CREATE USER</button></div></section><section className="card sectionSpace"><h2>Users & Roles</h2>{users.map(u=><div className="userline" key={u.id}><div><b>{u.display_name}</b><small>{u.email}</small></div><select value={u.role} onChange={e=>updateUser(u,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><button className={u.active?'secondary':'primary'} onClick={()=>updateUser(u,{active:!u.active})}>{u.active?'ACTIVE':'DISABLED'}</button></div>)}</section></>}
    {tab==='settings' && canStaff && <section className="card settingsCard"><h2>Event Settings</h2><div className="formgrid wide"><label>Event name<input value={localSettings.event_name} onChange={e=>setLocalSettings({...localSettings,event_name:e.target.value})}/></label><label>Currency symbol<input value={localSettings.currency_symbol} onChange={e=>setLocalSettings({...localSettings,currency_symbol:e.target.value})}/></label><label>Service day cutoff hour<input type="number" min="0" max="23" value={localSettings.service_day_cutoff_hour} onChange={e=>setLocalSettings({...localSettings,service_day_cutoff_hour:Number(e.target.value)})}/></label><label>Kitchen delay alert (minutes)<input type="number" min="1" max="180" value={localSettings.kitchen_delay_minutes} onChange={e=>setLocalSettings({...localSettings,kitchen_delay_minutes:Number(e.target.value)})}/></label><label>Max custom discount %<input type="number" min="0" max="100" value={localSettings.max_custom_discount_percent} onChange={e=>setLocalSettings({...localSettings,max_custom_discount_percent:Number(e.target.value)})}/></label></div><label className="checkRow"><input type="checkbox" checked={localSettings.require_cash_received} onChange={e=>setLocalSettings({...localSettings,require_cash_received:e.target.checked})}/> Require cash received to cover the order total</label><h3>Feature controls</h3><div className="featureGrid">{Object.entries(localSettings.features).map(([key,value])=><button key={key} className={'feature '+(value?'on':'off')} onClick={()=>featureToggle(key as keyof FeatureFlags)}><span>{featureLabels[key as keyof FeatureFlags]}</span><b>{value?'ON':'OFF'}</b></button>)}</div><button className="primary bigbtn" onClick={saveSettings}><Save size={17}/> SAVE SETTINGS</button></section>}
    {msg && <p className={msg.toLowerCase().includes('error')||msg.toLowerCase().includes('could not')?'error':'successText'}>{msg}</p>}
  </main>;
}
