'use client';
import {useEffect,useMemo,useState} from 'react';import {supabase} from '@/lib/supabase';import type {CartItem,Product} from '@/lib/types';
const money=(n:number)=>`₹${n}`;
export default function Cashier(){const [products,setProducts]=useState<Product[]>([]);const [cart,setCart]=useState<CartItem[]>([]);const [payment,setPayment]=useState<'cash'|'upi'>('cash');const [placing,setPlacing]=useState(false);const [last,setLast]=useState<number|null>(null);const [msg,setMsg]=useState('');
 useEffect(()=>{load();const ch=supabase.channel('cashier-products').on('postgres_changes',{event:'*',schema:'public',table:'products'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 async function load(){const {data}=await supabase.from('products').select('*').eq('active',true).order('station').order('created_at');if(data)setProducts(data as Product[])}
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.product.price*x.qty,0),[cart]);
 function add(p:Product){setCart(c=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,qty:i.qty+1}:i):[...c,{product:p,qty:1}]})}
 function change(id:string,d:number){setCart(c=>c.map(i=>i.product.id===id?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0))}
 async function place(){if(!cart.length)return;setPlacing(true);setMsg('');try{const payload=cart.map(x=>({product_id:x.product.id,qty:x.qty}));const {data:o,error}=await supabase.rpc('place_order',{p_total:total,p_payment_method:payment,p_items:payload});if(error)throw error;const order=o?.[0]||o;if(!order?.id)throw new Error('Order was not created');setCart([]);setLast(order.order_no);setMsg('Order sent to kitchen');}catch(e){setMsg(e instanceof Error?e.message:'Could not place order')}finally{setPlacing(false)}}
 return <main className="container"><div className="rolebar"><span>Cashier</span><span className="muted">Tap products to add</span></div><div className="grid"><section className="card"><h2>Menu</h2><div className="products">{products.map(p=><button className="product" key={p.id} onClick={()=>add(p)}><strong>{p.name}</strong><small className="station">{p.station}</small><span>{money(p.price)}</span></button>)}</div></section><aside className="card cart"><h2>Current Order</h2>{cart.length===0?<p className="muted">No items yet</p>:cart.map(x=><div className="cartline" key={x.product.id}><div><b>{x.product.name}</b><div className="muted">{money(x.product.price)} × {x.qty}</div></div><div className="qty"><button onClick={()=>change(x.product.id,-1)}>−</button><b>{x.qty}</b><button onClick={()=>change(x.product.id,1)}>+</button></div></div>)}<div className="payment"><b>Payment</b><div><button className={'choice '+(payment==='cash'?'selected':'')} onClick={()=>setPayment('cash')}>Cash</button><button className={'choice '+(payment==='upi'?'selected':'')} onClick={()=>setPayment('upi')}>UPI</button></div></div><div className="total">Total <b>{money(total)}</b></div><button className="primary bigbtn" disabled={placing||!cart.length} onClick={place}>{placing?'Sending…':'PLACE ORDER'}</button>{last&&<div className="ticket">ORDER <b>#{last}</b><small>Payment: {payment.toUpperCase()}</small></div>}{msg&&<p className={msg.includes('sent')?'successText':'error'}>{msg}</p>}</aside></div></main>}
