'use client';

import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { AppSettings, Order, OrderItem, Station } from '@/lib/types';

const stations: [Station|string,string][]=[['all','All'],['waffle','Waffle'],['chole','Chole Kulche'],['pav','Pav Bataka']];
export default function Kitchen({ settings }: { settings: AppSettings }) {
  const [orders,setOrders]=useState<Order[]>([]); const [station,setStation]=useState('all'); const [busy,setBusy]=useState<string|null>(null);
  useEffect(()=>{load();const ch=supabase.channel('kitchen-v2').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},load).subscribe();const timer=window.setInterval(load,30000);return()=>{supabase.removeChannel(ch);window.clearInterval(timer)}},[]);
  async function load(){const {data:o}=await supabase.from('orders').select('*').in('status',['new','preparing']).order('created_at',{ascending:true});if(!o){setOrders([]);return}const ids=o.map(x=>x.id);const {data:i}=ids.length?await supabase.from('order_items').select('*').in('order_id',ids):{data:[]};setOrders(o.map(x=>({...x,items:(i??[]).filter(y=>y.order_id===x.id)})) as Order[])}
  const visible=useMemo(()=>orders.filter(o=>o.items.some(i=>i.status!=='cancelled'&&(station==='all'||i.station===station))),[orders,station]);
  async function start(o:Order){const {error}=await supabase.rpc('start_order',{p_order_id:o.id});if(error)alert(error.message);load()}
  async function done(item:OrderItem){setBusy(item.id);const {error}=await supabase.rpc('complete_order_item',{p_item_id:item.id});if(error)alert(error.message);setBusy(null);load()}
  function age(created:string){return Math.floor((Date.now()-new Date(created).getTime())/60000)}
  return <main className="container"><div className="rolebar"><div><span>Kitchen Display</span><p className="hint">Live queue • tap each dish when it is ready.</p></div><span className="live">● LIVE</span></div><div className="tabs stationtabs">{stations.map(([k,n])=><button key={k} className={'tab '+(station===k?'active':'')} onClick={()=>setStation(k)}>{n}</button>)}</div><div className="ordergrid">{visible.map(o=>{const mins=age(o.created_at);const delayed=mins>=settings.kitchen_delay_minutes;const items=o.items.filter(i=>i.status!=='cancelled'&&(station==='all'||i.station===station));return <article className={'order kitchenOrder '+(delayed?'delayed ':'')+(o.token_no?'hasToken':'')} key={o.id}><div className="orderhead"><div><h2>#{o.order_no}</h2>{o.token_no&&<span className="tokenBadge">TOKEN {o.token_no}</span>}<span className="muted">{o.covers} cover{o.covers!==1?'s':''}</span></div><span className={delayed?'delayBadge':'ageBadge'}><Clock3 size={14}/> {mins}m</span></div>{delayed&&<div className="delayNotice">Waiting longer than the {settings.kitchen_delay_minutes}-minute alert threshold.</div>}{o.notes&&<div className="note">📝 {o.notes}</div>}<div className="orderitems">{items.map(i=><div className={'itemrow '+(i.status==='done'?'completed':'')} key={i.id}><span><b>{i.qty} × {i.product_name}</b><small>{i.station}</small></span>{i.status==='done'?<b className="successText"><CheckCircle2 size={18}/> DONE</b>:<button className="success small" disabled={busy===i.id} onClick={()=>done(i)}>{busy===i.id?'…':'READY'}</button>}</div>)}</div>{o.status==='new'&&<button className="primary bigbtn" onClick={()=>start(o)}>START ORDER</button>}</article>})}{!visible.length&&<div className="card empty"><h2>No pending orders 🎉</h2><p>Waiting for new orders.</p></div>}</div></main>;
}
