'use client';
import {useEffect,useMemo,useState} from 'react';import {supabase} from '@/lib/supabase';import type {Order,OrderItem,Station as StationType} from '@/lib/types';
const stations:[StationType|string,string][]=[['all','All'],['waffle','Waffle'],['chole','Chole Kulche'],['pav','Pav Bataka']];
export default function Kitchen(){const [orders,setOrders]=useState<Order[]>([]);const [station,setStation]=useState('all');const [busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{load();const ch=supabase.channel('kitchen-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 async function load(){const {data:o}=await supabase.from('orders').select('*').in('status',['new','preparing']).order('created_at',{ascending:true});if(!o){setOrders([]);return}const ids=o.map(x=>x.id);const {data:i}=ids.length?await supabase.from('order_items').select('*').in('order_id',ids):{data:[]};setOrders(o.map(x=>({...x,items:(i||[]).filter(y=>y.order_id===x.id)})) as Order[])}
 const visible=useMemo(()=>orders.filter(o=>o.items.some(i=>station==='all'||i.station===station)),[orders,station]);
 async function start(o:Order){await supabase.from('orders').update({status:'preparing'}).eq('id',o.id);load()}
 async function done(item:OrderItem){setBusy(item.id);await supabase.from('order_items').update({status:'done'}).eq('id',item.id);const {data:left}=await supabase.from('order_items').select('id').eq('order_id',item.order_id).neq('status','done');if(!left?.length)await supabase.from('orders').update({status:'ready'}).eq('id',item.order_id);else await supabase.from('orders').update({status:'preparing'}).eq('id',item.order_id);setBusy(null);load()}
 return <main className="container"><div className="rolebar"><span>Kitchen Display</span><span className="muted">Live • oldest orders first</span></div><div className="tabs stationtabs">{stations.map(([k,n])=><button key={k} className={'tab '+(station===k?'active':'')} onClick={()=>setStation(k)}>{n}</button>)}</div><div className="ordergrid">{visible.map(o=>{const items=o.items.filter(i=>station==='all'||i.station===station);return <article className="order" key={o.id}><div className="orderhead"><h2>#{o.order_no}</h2><span className="station">{new Date(o.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><div className="orderitems">{items.map(i=><div className={'itemrow '+(i.status==='done'?'completed':'')} key={i.id}><span><b>{i.qty} × {i.product_name}</b></span>{i.status==='done'?<b className="successText">✓ DONE</b>:<button className="success bigbtn small" disabled={busy===i.id} onClick={()=>done(i)}>{busy===i.id?'…':'DONE'}</button>}</div>)}</div>{o.status==='new'&&<button className="primary" onClick={()=>start(o)}>START ORDER</button>}</article>})}</div>{!visible.length&&<div className="card empty"><h2>No pending orders 🎉</h2></div>}</main>}
