'use client';

import { useEffect, useState } from 'react';
import { Printer, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { AppSettings, Order, OrderItem, Profile } from '@/lib/types';
import { money } from '@/lib/format';

export default function Orders({ settings, profile }: { settings: AppSettings; profile: Profile }) {
  const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all');
  useEffect(()=>{load();const ch=supabase.channel('orders-v2').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},load).subscribe();return()=>{supabase.removeChannel(ch)};},[]);
  async function load(){setLoading(true);const {data:o}=await supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(!o){setOrders([]);setLoading(false);return}const ids=o.map(x=>x.id);const {data:i}=ids.length?await supabase.from('order_items').select('*').in('order_id',ids):{data:[]};setOrders(o.map(x=>({...x,items:(i??[]).filter(y=>y.order_id===x.id)})) as Order[]);setLoading(false)}
  const filtered=orders.filter(o=>(status==='all'||o.status===status)&&(!search||String(o.order_no).includes(search)||(o.token_no??'').toLowerCase().includes(search.toLowerCase())||o.items.some(i=>i.product_name.toLowerCase().includes(search.toLowerCase()))));
  async function cancelLine(item:OrderItem){const reason=window.prompt('Reason for cancelling this line?','Mis-tap');if(reason===null)return;setBusy(item.id);const {error}=await supabase.rpc('cancel_order_item',{p_item_id:item.id,p_reason:reason});setBusy(null);if(error)alert(error.message);else load();}
  async function cancelOrder(o:Order){const reason=window.prompt(`Cancel order #${o.order_no}? Reason:`,'Customer cancelled');if(reason===null)return;setBusy(o.id);const {error}=await supabase.rpc('cancel_order',{p_order_id:o.id,p_reason:reason});setBusy(null);if(error)alert(error.message);else load();}
  function print(o:Order){const activeItems=o.items.filter(i=>i.status!=='cancelled');const html=`<!doctype html><html><head><title>Order #${o.order_no}</title><style>body{font-family:Arial;width:330px;margin:20px auto}div{display:flex;justify-content:space-between;margin:7px 0}.c{text-align:center}hr{border:0;border-top:1px dashed #000}</style></head><body><h2 class="c">${settings.event_name}</h2><div><b>ORDER #${o.order_no}</b><span>${new Date(o.created_at).toLocaleTimeString()}</span></div>${o.token_no?`<p style=\"font-size:22px;font-weight:bold;border:2px solid #000;padding:6px;text-align:center\">TOKEN ${o.token_no}</p>`:''}<p>Covers: ${o.covers}</p>${activeItems.map(i=>`<div><span>${i.qty} × ${i.product_name}</span><span>${money(i.price*i.qty,settings.currency_symbol)}</span></div>`).join('')}<hr>${o.discount_amount?`<div><span>Discount</span><b>-${money(o.discount_amount,settings.currency_symbol)}</b></div>`:''}<div><b>Total</b><b>${money(o.total,settings.currency_symbol)}</b></div><p>Payment: ${o.payment_method.toUpperCase()}</p><p>${o.notes||''}</p></body></html>`;const w=window.open('','_blank','width=380,height=640');if(w){w.document.write(html);w.document.close();w.focus();w.print()}}

  return <main className="container"><div className="rolebar"><div><span>Order Management</span><p className="hint">Review, print and correct orders without hiding history.</p></div></div><div className="toolbar"><input className="search" placeholder="Search order #, token or item" value={search} onChange={e=>setSearch(e.target.value)}/>{['all','new','preparing','ready','cancelled'].map(s=><button key={s} className={'choice '+(status===s?'selected':'')} onClick={()=>setStatus(s)}>{s.toUpperCase()}</button>)}</div><section className="orderList sectionSpace">{loading&&<div className="card">Loading orders…</div>}{!loading&&!filtered.length&&<div className="card empty"><h2>No matching orders</h2></div>}{filtered.map(o=><article className={'card orderDetail '+(o.status==='cancelled'?'cancelled ':'')+(o.token_no?'hasToken':'')} key={o.id}><div className="orderhead"><div><h2>#{o.order_no}{o.token_no&&<span className="tokenBadge">TOKEN {o.token_no}</span>}</h2><small>{new Date(o.created_at).toLocaleString()} • {o.covers} cover{o.covers!==1?'s':''}</small></div><div className="orderActions"><span className={'status '+o.status}>{o.status}</span>{settings.features.printing&&<button className="secondary" onClick={()=>print(o)}><Printer size={16}/></button>}{o.status!=='cancelled'&&<button className="dangerBtn" disabled={busy===o.id||profile.role==='cashier'&&o.created_by!==profile.id} onClick={()=>cancelOrder(o)} title={profile.role==='cashier'&&o.created_by!==profile.id?'Cashiers can cancel only their own orders':''}><XCircle size={16}/> Cancel</button>}</div></div>{o.notes&&<div className="note">📝 {o.notes}</div>}{o.items.map(i=><div className={'itemrow '+(i.status==='cancelled'?'completed':'')} key={i.id}><span>{i.qty} × <b>{i.product_name}</b><small>{money(i.price,settings.currency_symbol)} each</small></span><span>{i.status==='cancelled'?<span className="status cancelledTxt">CANCELLED</span>:o.status!=='cancelled'&&<button className="linkDanger" disabled={busy===i.id} onClick={()=>cancelLine(i)}>Cancel line</button>}</span></div>)}<div className="summaryLine"><span>{o.discount_amount?'Subtotal / Discount / Total':'Total'}</span><b>{o.discount_amount?`${money(o.subtotal,settings.currency_symbol)} / -${money(o.discount_amount,settings.currency_symbol)} / ${money(o.total,settings.currency_symbol)}`:money(o.total,settings.currency_symbol)}</b></div></article>)}</section></main>;
}
